import style from './Countries.module.scss'

import { Country } from '../Country'
import { CountriesQL } from "../../types"
import { Pages } from "../../configuration/common"
import Head from "next/head";

export const Countries = ({countries}: {countries: CountriesQL[]}) => {
  return (
    <>
      <Head>
        <title>{Pages.Guide.headline}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <h2>{Pages.Guide.headline}</h2>
        <div className={style.Card}>
          {
            countries?.map((country: CountriesQL, idx: number) => {
              return (
                <div
                  className={style.Box}
                  key={idx}
                  >
                  <Country {...country} />
                </div>
              )
            })
          }
        </div>
      </div>
    </>
  )
}
