import '../styles/index.scss'

import type { AppProps } from 'next/app'
import { Provider } from 'react-redux'
import apolloClient from '../apollo/graphql-client'
import { ApolloProvider } from '@apollo/client'
import { store } from '../store'
import { DateBox, Header, Main, Navigation, Theme } from '../components'
import { navigationLinks } from '../configuration'
import { useState } from 'react'
import Head from 'next/head'
import { useRouter } from 'next/router'
import { SubNavMedia } from './subNavigationMedia/subNavMedia'

export default function MyApp({ Component, pageProps }: AppProps) {
  const router = useRouter()
  const SubNavigationMedia = SubNavMedia(router.pathname)

  return (
    <Provider store={store}>
      <ApolloProvider client={apolloClient}>
        <Head>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Header>
          <DateBox />
          <Theme ariaLabel={'controlled'} />
        </Header>
        <Navigation isMain={true} links={navigationLinks} />
        {SubNavigationMedia}

        <Main>
          <Component {...pageProps} />
        </Main>
      </ApolloProvider>
    </Provider>
  )
}
