import type { NextPage } from 'next'
import Head from 'next/head'
import useTranslation from "next-translate/useTranslation"

const Home: NextPage = () => {
  const { t } = useTranslation('common')

  return (
    <>
      <Head>
        <title>{t('welcome')}</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
    </>
  )
}

export default Home
