import { Car } from '../Car'
import { CarsInit } from "../../types"
import { Pages } from '../../configuration/common'
import Head from "next/head"

type Props = {
  cars: CarsInit[]
}

export const Cars = ({cars}: Props) => {
  return (
    <>
      <Head>
        <title>{Pages.Guide.chSeven.headline}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {cars?.map((car, idx: number) => {
        return (
          <Car {...car} key={idx} />
        )
      })
      }
    </>
  )
}
